### ISSUE TITLE
Allow compatibility with Symfony 2.3

### ISSUE THREAD

**Issue by stefk** [IDCI-Consulting/ExporterBundle#2]
The current version constraint for "symfony/framework-bundle" specified in the composer.json file doesn't allow this bundle to be installed in a 2.3 environment. Is an upgrade possible ? Thanks.

**Comment by konandrum** [comment]
I will do this asap

**Comment by konandrum** [comment]
Must be done, not yet tested

**Comment by stefk** [comment]
It didn't break anything for us at least :) Thanks
